### ISSUE TITLE
Error inserting module

### ISSUE THREAD

**Issue by phantomcraft** [upa/af-graft#1]
After compiling the package I try to load the module but I get an error:

$ insmod kmod/af_graft.ko 
insmod: ERROR: could not insert module kmod/af_graft.ko: File exists

No error found in dmesg and "journalctl -xe", but in /var/log/kern:

Oct 15 18:22:11 localhost kernel: [ 8810.983059] NET: Registered protocol family 4
Oct 15 18:22:11 localhost kernel: [ 8810.983061] af_graft: af_graft_init: sock_register failed '-17'

My system is Debian Testing with kernel 4.16.0-1-amd64, gcc version 8.2.0.

=============================

Here is strace log:

$ strace insmod kmod/af_graft.ko 
execve("/sbin/insmod", ["insmod", "kmod/af_graft.ko"], 0x7ffeb30520c8 /* 23 vars */) = 0
brk(NULL)                               = 0x55de07883000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=314313, ...}) = 0
mmap(NULL, 314313, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f57bf9e2000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/liblzma.so.5", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\2200\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=154376, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f57bf9e0000
mmap(NULL, 2249360, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f57bf7ba000
mprotect(0x7f57bf7df000, 2093056, PROT_NONE) = 0
mmap(0x7f57bf9de000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x24000) = 0x7f57bf9de000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000,\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1808440, ...}) = 0
mmap(NULL, 1821408, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f57bf5fd000
mmap(0x7f57bf61f000, 1335296, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x22000) = 0x7f57bf61f000
mmap(0x7f57bf765000, 307200, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x168000) = 0x7f57bf765000
mmap(0x7f57bf7b0000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1b2000) = 0x7f57bf7b0000
mmap(0x7f57bf7b6000, 15072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f57bf7b6000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\21\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14592, ...}) = 0
mmap(NULL, 16656, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f57bf5f8000
mmap(0x7f57bf5f9000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1000) = 0x7f57bf5f9000
mmap(0x7f57bf5fa000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f57bf5fa000
mmap(0x7f57bf5fb000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f57bf5fb000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300k\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=146312, ...}) = 0
mmap(NULL, 132224, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f57bf5d7000
mmap(0x7f57bf5dd000, 61440, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6000) = 0x7f57bf5dd000
mmap(0x7f57bf5ec000, 24576, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7f57bf5ec000
mmap(0x7f57bf5f2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a000) = 0x7f57bf5f2000
mmap(0x7f57bf5f4000, 13440, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f57bf5f4000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f57bf5d5000
arch_prctl(ARCH_SET_FS, 0x7f57bf5d5b80) = 0
mprotect(0x7f57bf7b0000, 16384, PROT_READ) = 0
mprotect(0x7f57bf5f2000, 4096, PROT_READ) = 0
mprotect(0x7f57bf5fb000, 4096, PROT_READ) = 0
mprotect(0x7f57bf9de000, 4096, PROT_READ) = 0
mprotect(0x55de0602f000, 8192, PROT_READ) = 0
mprotect(0x7f57bfa56000, 4096, PROT_READ) = 0
munmap(0x7f57bf9e2000, 314313)          = 0
set_tid_address(0x7f57bf5d5e50)         = 18420
set_robust_list(0x7f57bf5d5e60, 24)     = 0
rt_sigaction(SIGRTMIN, {sa_handler=0x7f57bf5dd630, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f57bf5e98e0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7f57bf5dd6d0, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x7f57bf5e98e0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(NULL)                               = 0x55de07883000
brk(0x55de078a4000)                     = 0x55de078a4000
uname({sysname="Linux", nodename="localhost", ...}) = 0
openat(AT_FDCWD, "/lib/modules/4.16.0-1-amd64/modules.softdep", O_RDONLY|O_CLOEXEC) = 3
fcntl(3, F_GETFL)                       = 0x8000 (flags O_RDONLY|O_LARGEFILE)
fstat(3, {st_mode=S_IFREG|0644, st_size=768, ...}) = 0
read(3, "# Soft dependencies extracted fr"..., 4096) = 768
read(3, "", 4096)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/proc/cmdline", O_RDONLY|O_CLOEXEC) = 3
read(3, "BOOT_IMAGE=/vmlinuz-4.16.0-1-amd"..., 4095) = 91
read(3, "", 4004)                       = 0
close(3)                                = 0
stat(".", {st_mode=S_IFDIR|0755, st_size=154, ...}) = 0
stat("/home/user/Store/Programs/Programs/af-graft/af-graft-master", {st_mode=S_IFDIR|0755, st_size=154, ...}) = 0
stat("/home/user/Store/Programs/Programs/af-graft/af-graft-master/kmod/af_graft.ko", {st_mode=S_IFREG|0644, st_size=671800, ...}) = 0
openat(AT_FDCWD, "/home/user/Store/Programs/Programs/af-graft/af-graft-master/kmod/af_graft.ko", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1", 6)               = 6
lseek(3, 0, SEEK_SET)                   = 0
fstat(3, {st_mode=S_IFREG|0644, st_size=671800, ...}) = 0
mmap(NULL, 671800, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f57bf530000
finit_module(3, "", 0)                  = -1 EEXIST (File exists)
write(2, "insmod: ERROR: could not insert "..., 69insmod: ERROR: could not insert module kmod/af_graft.ko: File exists
) = 69
munmap(0x7f57bf530000, 671800)          = 0
close(3)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++

=====================

ltrace log:

$ ltrace insmod kmod/af_graft.ko 
[...]
strtok_r(0x55bc46694650, 0x55bc45102b62, 0x7ffce8d9d7a8, 256)                                                                             = 0x55bc46694650
strtok_r(0, 0x55bc45102b62, 0x7ffce8d9d7a8, 0)                                                                                            = 0x55bc46694658
strtok_r(0, 0x55bc45104599, 0x7ffce8d9d7a8, 1)                                                                                            = 0x55bc46694662
strlen("libcrc32c")                                                                                                                       = 9
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
malloc(57)                                                                                                                                = 0x55bc46696080
memcpy(0x55bc466960a8, "libcrc32c\0", 10)                                                                                                 = 0x55bc466960a8
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
__ctype_b_loc()                                                                                                                           = 0x7f14aea97b18
memcpy(0x55bc466960b2, "crc32c", 6)                                                                                                       = 0x55bc466960b2
malloc(24)                                                                                                                                = 0x55bc466960d0
free(0x55bc46694650)                                                                                                                      = <void>
malloc(256)                                                                                                                               = 0x55bc46694650
__uflow(0x55bc46694420, 0x55bc46694088, 0x55bc46694650, 256)                                                                              = -1
free(0x55bc46694650)                                                                                                                      = <void>
fclose(0x55bc46694420)                                                                                                                    = 0
free(0x55bc46694380)                                                                                                                      = <void>
free(0x55bc466943b0)                                                                                                                      = <void>
open("/proc/cmdline", 524288, 00)                                                                                                         = 3
read(3, "BOOT_IMAGE=/vmlinuz-4.16.0-1-amd"..., 4095)                                                                                      = 91
read(3, "", 4004)                                                                                                                         = 0
close(3)                                                                                                                                  = 0
calloc(1, 4120)                                                                                                                           = 0x55bc466960f0
get_current_dir_name(0x7ffce8d9edf5, 0x7ffce8d9edf5, 0x7ffce8d9e900, 0)                                                                   = 0x55bc46694760
strlen("kmod/af_graft.ko")                                                                                                                = 16
strlen("/home/user/Store/Programs/Progra"...)                                                                                             = 59
realloc(0x55bc46694760, 77)                                                                                                               = 0x55bc46694760
memcpy(0x55bc4669479c, "kmod/af_graft.ko\0", 17)                                                                                          = 0x55bc4669479c
free(0)                                                                                                                                   = <void>
__xstat(1, "/home/user/Store/Programs/Progra"..., 0x7ffce8d9d890)                                                                         = 0
basename("kmod/af_graft.ko")                                                                                                              = "af_graft.ko"
strlen("af_graft")                                                                                                                        = 8
strlen("af_graft")                                                                                                                        = 8
malloc(113)                                                                                                                               = 0x55bc466947c0
memcpy(0x55bc46694828, "af_graft\0", 9)                                                                                                   = 0x55bc46694828
strlen("af_graft")                                                                                                                        = 8
realloc(0, 128)                                                                                                                           = 0x55bc46694840
calloc(1, 56)                                                                                                                             = 0x55bc466948d0
open("/home/user/Store/Programs/Progra"..., 524288, 070)                                                                                  = 3
read(3, "\177ELF\002\001", 6)                                                                                                             = 6
lseek(3, 0, 0)                                                                                                                            = 0
memcmp(0x7ffce8d9e8c0, 0x55bc45105290, 6, 0x7f14aeba8367)                                                                                 = 0xffffff82
__fxstat(1, 3, 0x7ffce8d9e810)                                                                                                            = 0
mmap(0, 0xa4038, 1, 2)                                                                                                                    = 0x7f14ae9f2000
syscall(313, 3, 0x55bc45102a78, 0)                                                                                                        = -1
__errno_location()                                                                                                                        = 0x7f14aea97b00
__errno_location()                                                                                                                        = 0x7f14aea97b00
strerror(17)                                                                                                                              = "File exists"
__vasprintf_chk(0x7ffce8d9e850, 1, 0x55bc45100e78, 0x7ffce8d9e858)                                                                        = 54
__fprintf_chk(0x7f14aec77680, 1, 0x55bc45103906, 0x7ffce8d9edeeinsmod: ERROR: could not insert module kmod/af_graft.ko: File exists
)                                                                          = 69
free(0x55bc46694910)                                                                                                                      = <void>
strlen("af_graft")                                                                                                                        = 8
strcmp("af_graft", "af_graft")                                                                                                            = 0
memmove(0x55bc46694840, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 16)                                                                           = 0x55bc46694840
munmap(0x7f14ae9f2000, 0xa4038, 0, 0x55bc466960f0)                                                                                        = 0
close(3)                                                                                                                                  = 0
free(0x55bc466948d0)                                                                                                                      = <void>
free(0)                                                                                                                                   = <void>
free(0x55bc46694760)                                                                                                                      = <void>
free(0x55bc466947c0)                                                                                                                      = <void>
free(0)                                                                                                                                   = <void>
free(0)                                                                                                                                   = <void>
free(0)                                                                                                                                   = <void>
free(0)                                                                                                                                   = <void>
free(0)                                                                                                                                   = <void>
free(0)                                                                                                                                   = <void>
free(0)                                                                                                                                   = <void>
free(0)                                                                                                                                   = <void>
free(0)                                                                                                                                   = <void>
free(0x55bc46694840)                                                                                                                      = <void>
free(0)                                                                                                                                   = <void>
[...]

**Comment by upa** [comment]
Current implementation overrides AF_IPX withAF_GRAFT becuase Linux kernel prohibits dinamically adding a new address family number (please see include graft.h).

af_graft_init: sock_register failed '-17' (-EEXIST) indicates that a socket protocol family is already registered in the address family number, which is AF_IPX.

So, please `modprobe -r ipx`.

**Comment by phantomcraft** [comment]
It solved, thank you.

I suggest to include this detail in README.

**Comment by upa** [comment]
Yes, I added ;) thank you.
