### ISSUE TITLE
Correct way for testing performing tests

### ISSUE THREAD

**Issue by aneesh-joshi** [upa/af-graft#6]
Hi,
I am trying to test af-graft and see the performance gain myself.
I have created a VM with the graft end points and everything as mentioned in the readme.

However, when I test with iperf3, I get almost the same performance for socket grafter docker iperf3 server and non-socket grafted iperf3 server (taken from [here](https://hub.docker.com/r/networkstatic/iperf3/))

I would expect the grafted one to be significantly. Note : the server is set up as per the readme in docker/

Is there something I am missing?

Thanks!

**Comment by phantomcraft** [comment]
I didn't understand your English very well, but if the performance is the same of non-grafted this is perfectly ok. Here I get a speed of 48GBps with grafted iperf3 while non-grafted gives 44~46GBps.

**Comment by aneesh-joshi** [comment]
I was hoping to see a significant difference in performance between the grafted and non grafted scenarios. What is the reason for not seeing it? Are the values expected to be close by?

**Comment by phantomcraft** [comment]
@aneesh-joshi 

Yes, af_graft is a low-level bypass for network programs inside network namespaces, Docker (and LXC) is just a flavored netns.

Here is a test with grafted iperf3:

**_/opt/af-graft/iproute2-4.19.0/ip/ip add in4 type ipv4 addr 127.0.0.1 port 5201 netns 1 
/opt/af-graft/iproute2-4.19.0/ip/ip add out4 type ipv4 addr 0.0.0.0 port dynamic netns 1 
LD_PRELOAD="/opt/af-graft/tools/libgraft-convert.so" GRAFT_VERBOSE="0" GRAFT_EGRESS_CONVERT="0.0.0.0/0=out4" GRAFT_INGRESS_CONVERT="127.0.0.1:5201=in4" iperf3 -s -B 127.0.0.1 - 5201_**

_**LD_PRELOAD="/opt/af-graft/tools/libgraft-convert.so" GRAFT_VERBOSE="0" GRAFT_EGRESS_CONVERT="0.0.0.0/0=out4" iperf3 -c 127.0.0.1 -p 5201 -t 120**_
Connecting to host 127.0.0.1, port 5201
[  5] local 127.0.0.1 port 54171 connected to 127.0.0.1 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  4.99 GBytes  42.9 Gbits/sec    0    639 KBytes       
[  5]   1.00-2.00   sec  4.80 GBytes  41.3 Gbits/sec    0    639 KBytes       
[  5]   2.00-3.00   sec  4.97 GBytes  42.7 Gbits/sec    1    512 KBytes       
[...]
[  5] 117.00-118.00 sec  4.84 GBytes  41.5 Gbits/sec    0    639 KBytes       
[  5] 118.00-119.00 sec  4.79 GBytes  41.1 Gbits/sec    0    639 KBytes       
[  5] 119.00-120.00 sec  4.95 GBytes  42.5 Gbits/sec    0    639 KBytes       
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-120.00 sec   588 GBytes  42.1 Gbits/sec    2             sender
[  5]   0.00-120.04 sec   588 GBytes  42.1 Gbits/sec                  receiver
iperf Done.

Non-grafted:

**_iperf3 -s -B 127.0.0.1 -p 5201
iperf3 -c 127.0.0.1 -p 5201 -t 120_**
Connecting to host 127.0.0.1, port 5201
[  5] local 127.0.0.1 port 46384 connected to 127.0.0.1 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  4.77 GBytes  41.0 Gbits/sec    0    639 KBytes       
[  5]   1.00-2.00   sec  4.71 GBytes  40.5 Gbits/sec    0    639 KBytes       
[  5]   2.00-3.00   sec  4.96 GBytes  42.6 Gbits/sec    0    639 KBytes       
[...]     
[  5] 117.00-118.00 sec  4.95 GBytes  42.6 Gbits/sec    0    639 KBytes       
[  5] 118.00-119.00 sec  5.03 GBytes  43.2 Gbits/sec    0    639 KBytes       
[  5] 119.00-120.00 sec  4.87 GBytes  41.9 Gbits/sec    0    639 KBytes       
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-120.00 sec   591 GBytes  42.3 Gbits/sec    3             sender
[  5]   0.00-120.04 sec   591 GBytes  42.3 Gbits/sec                  receiver
iperf Done.

-------------------------

I don't know why but some time ago when I was using kernel 4.17.x I was getting  3 Gbits more with grafted iperf3.

(I hate markdown =] )

**Comment by aneesh-joshi** [comment]
Thanks for the information.
